# Site settings
title: Susana Mariel Lopez
name: Mariel Lopez

# Build settings
markdown: kramdow

#Any buzzword skills you want to include
skills:
 - API design
 - Java
 - SQL
 - REST
 - React JS
 - JavaScript
 - mySQL
 - Neo4J
 - HTML
 - NODE JS 
 - PHP
 - REACT JS 
 - BOOTSTRAP
 - CSS
 - Docker 

#Work experience is required
roles:
 - title: Administrativa
   start: 2015
   end: 2017
   employer: Municipalidad de Quilmes
   description: Atencion al vecino (de manera telefonica y personal) y mesa de informes.
 - title: Soporte Tecnico
   start: 2012
   end: 2012
   employer: Universidad Nacional de Quilmes
   description: Pasantia en el area de soporte técnico en la universidad (reparacion, control de ingresos y egresos de los equipos).
 
#Education is required
education:
 - level: Licenciatura en Informatica con orientacion a desarrollo de software
   date: 2014 - ACTUALIDAD
   school: Universidad Nacional de Quilmes
 - level: Tecnicatura en Programacion Informatica
   date: 2014 - ACTUALIDAD
   school: Universidad Nacional de Quilmes

#List of interesting Github repo/projects to include - optional
github:
 - MaarLop/MaarLop.github.io
 - MaarLop/buscador-react

intro: Soy estudiante de la Universidad Nacional de Quilmes. Me encuentro cursando las carreras de Técnica en Programación Informática y Licenciatura en Informática, de las cuales
llevo aprobadas 18 materias hasta la fecha.
Apunto a ser una desarrolladora fullstack, ya que me siento muy comoda trabajando en ambos extremos.
#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Java</strong>: He desarrollado mucho de mi carrera en Java en cuanto a OOP, y la trabaje conjunto con Hibernet, Neo4j, M<br/><br/>
   <strong>Web Development</strong>: Aplicacines desarrolladas en JavaScript, Node JS , React JS, Css y Bootstrap consumiend y brindando servicios API REST<br/><br/>

   